version: '3'

services:

  api:
    build:
      context: api
      dockerfile: Dockerfile
    command: /bin/bash ./run.sh
    volumes:
      - ./api/:/code
    ports:
      - 9000:9000
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
